FROM centos:7
RUN yum install -y kernel-devel kernel
RUN yum install -y epel-release
RUN sync
# RUN shutdown -r now
# RUN yum install -y https://s3.amazonaws.com/archive.zfsonlinux.org/epel/zfs-release.el7.noarch.rpm
# RUN yum install -y https://s3.amazonaws.com/clusterhq-archive/centos/clusterhq-release$(rpm -E %dist).noarch.rpm
# RUN yum install -y clusterhq-flocker-node
